# Generated by Django 5.0.6 on 2024-12-02 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.director'),
        ),
    ]
